use_frameworks!

platform :ios, '10.0'

target 'nvServiceExtSampleTest_Example' do
  pod 'nvServiceExtSampleTest', :path => '../'

  target 'nvServiceExtSampleTest_Tests' do
    inherit! :search_paths

    
  end
end
